/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118858-g740d400965-20250318"
#endif /* AVUTIL_FFVERSION_H */
